config/routes.rb
Rails.application.routes.draw do
  
  #get 'managers/index'
  #get 'managers/list'
  #get 'managers/add'
  #get 'managers/edit'
  #get 'managers/delete'
  devise_for :users
  resources :managers
  resources :items
  resources :mainsuppliers
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "managers#index"
  get "/beers", to: "managers#beers"
  get "/fruits", to: "managers#fruits"
  get "/items", to: "managers#items"
  get "/mainsuppliers", to: "managers#mainsuppliers"


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/item.rb
class Item < ApplicationRecord
    #Set up relationships with suppliers
    #belongs_to :Mainsupplier, class_name: 'Mainsupplier'
    


    #Validation for product name
    validates :name,
      :presence=> {:message=> "can't be empty" },
      :length=> { minimum: 2 }
end

app/models/item_observer.rb
class ItemObserver < ActiveRecord::Observer
    def after_create(item)

    end

    def after_update(item)

    end

    def after_destroy(item)

    end
end

app/models/mainsupplier.rb
class Mainsupplier < ApplicationRecord

    #set up relationships with items
    #has_many :items, class_name: "Item"    

    #validations for supplier name
    validates :name,
    :presence=> {:message=> "can't be empty" },
    :length=> { minimum: 2 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
       devise :database_authenticatable, :registerable,
              :recoverable, :rememberable, :validatable
  
       VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  
       validates :email, length: { maximum: 255 },
              :presence => { :message  => "Can't be empty" },
              :format => { with: VALID_EMAIL_REGEX, :message => "Invalid format"},
              uniqueness: { case_sensitive: false }

       enum role: [:user, :moderator, :admin]
       after_initialize :set_default_role, :if => :new_record?
       def set_default_role
              self.role ||= :user
       end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: %i[ show edit update destroy ]
  before_action :authenticate_user! #, except: [:show, :edit, :update, :destroy]

  # GET /items or /items.json
  def index
    @items = Item.all
  end

  # GET /items/1 or /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
    #observer design pattern
  end

  # POST /items or /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to item_url(@item), notice: "Item was successfully created." }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1 or /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to item_url(@item), notice: "Item was successfully updated." }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1 or /items/1.json
  def destroy
    @item.destroy

    respond_to do |format|
      format.html { redirect_to items_url, notice: "Item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def item_params
      params.require(:item).permit(:name, :description, :quantity)
    end
end

app/controllers/mainsuppliers_controller.rb
class MainsuppliersController < ApplicationController
  before_action :set_mainsupplier, only: %i[ show edit update destroy ]
  before_action :authenticate_user! #, except: [:show, :edit, :update, :destroy]
  
  # GET /mainsuppliers or /mainsuppliers.json
  def index
    @mainsuppliers = Mainsupplier.all
  end

  # GET /mainsuppliers/1 or /mainsuppliers/1.json
  def show
  end

  # GET /mainsuppliers/new
  def new
    @mainsupplier = Mainsupplier.new
  end

  # GET /mainsuppliers/1/edit
  def edit
  end

  # POST /mainsuppliers or /mainsuppliers.json
  def create
    @mainsupplier = Mainsupplier.new(mainsupplier_params)

    respond_to do |format|
      if @mainsupplier.save
        format.html { redirect_to mainsupplier_url(@mainsupplier), notice: "Mainsupplier was successfully created." }
        format.json { render :show, status: :created, location: @mainsupplier }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @mainsupplier.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mainsuppliers/1 or /mainsuppliers/1.json
  def update
    respond_to do |format|
      if @mainsupplier.update(mainsupplier_params)
        format.html { redirect_to mainsupplier_url(@mainsupplier), notice: "Mainsupplier was successfully updated." }
        format.json { render :show, status: :ok, location: @mainsupplier }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @mainsupplier.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mainsuppliers/1 or /mainsuppliers/1.json
  def destroy
    @mainsupplier.destroy

    respond_to do |format|
      format.html { redirect_to mainsuppliers_url, notice: "Mainsupplier was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mainsupplier
      @mainsupplier = Mainsupplier.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def mainsupplier_params
      params.require(:mainsupplier).permit(:name, :supply)
    end
end

app/controllers/managers_controller.rb
class ManagersController < ApplicationController
  def index
  end
  
  def beers
    beers = HTTParty.get("https://api.punkapi.com/v2/beers")
    @beers = JSON.parse(beers.body)
  end
  
  def fruits
    fruits = HTTParty.get("https://fruityvice.com/api/fruit/all")
    @fruits = JSON.parse(fruits.body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/mainsuppliers_helper.rb
module MainsuppliersHelper
end

app/helpers/managers_helper.rb
module ManagersHelper
end

app/views/items/_form.html.erb
<%= form_with(model: item) do |form| %>
  <% if item.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
        <% item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :quantity, style: "display: block" %>
    <%= form.number_field :quantity %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/items/_item.html.erb
<div id="<%= dom_id item %>">
  <p>
    <strong>Name:</strong>
    <%= item.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= item.description %>
  </p>

  <p>
    <strong>Quantity:</strong>
    <%= item.quantity %>
  </p>
</div>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render "form", item: @item %>

<br>

<div>
  <%= link_to "Show this item", @item %> |
  <%= link_to "Back to items", items_path %>
</div>

app/views/items/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Items</h1>

<div id="items">
  <% @items.each do |item| %>
    <%= render item %>
    <p>
      <%= link_to "Show this item", item %>
    </p>
  <% end %>
</div>

<%= link_to "New item", new_item_path %>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render "form", item: @item %>

<br>

<div>
  <%= link_to "Back to items", items_path %>
</div>

app/views/items/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @item %>

<div>
  <%= link_to "Edit this item", edit_item_path(@item) %> |
  <%= link_to "Back to items", items_path %>

  <%= button_to "Destroy this item", @item,  method: :delete %>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
      <a class="navbar-brand" href="/">Inventory Manager</a>
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="/beers">Browse beers</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/fruits">Browse fruit</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/items">Manage Items</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/mainsuppliers">Suppliers</a>
        </li>
        <% if current_user %>
          <li class="nav-item"> <%= link_to "Edit Account", edit_user_registration_path, class: "nav-link" %></li>
          <li class="nav-item"> <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-small btn-primary mx-2" %></li>
        <% else %>
          <li class="nav-item"> <%= link_to "Sign Up", new_user_registration_path, class: "nav-link"  %></li>
          <li class="nav-item"> <%= link_to "Sign In", new_user_session_path, class: "nav-link"  %></li>
        <% end %>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InventoryManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
  <%= render 'layouts/navbar' %>
  <div class="container-fluid">
    <p class="notice"><%= notice %></p> 
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </div>
  </body>
</html>

app/views/mainsuppliers/_form.html.erb
<%= form_with(model: mainsupplier) do |form| %>
  <% if mainsupplier.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(mainsupplier.errors.count, "error") %> prohibited this mainsupplier from being saved:</h2>

      <ul>
        <% mainsupplier.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :supply, style: "display: block" %>
    <%= form.text_field :supply %>
  </div>
  <div>
    <%= form.submit %>
  </div>

<% end %>

app/views/mainsuppliers/_mainsupplier.html.erb
<div id="<%= dom_id mainsupplier %>">
  <p>
    <strong>Name:</strong>
    <%= mainsupplier.name %>
  </p>

  <p>
    <strong>Supply:</strong>
    <%= mainsupplier.supply %>
  </p>

</div>

app/views/mainsuppliers/edit.html.erb
<h1>Editing mainsupplier</h1>

<%= render "form", mainsupplier: @mainsupplier %>

<br>

<div>
  <%= link_to "Show this supplier", @mainsupplier %> |
  <%= link_to "Back to suppliers", mainsuppliers_path %>
</div>

app/views/mainsuppliers/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Main suppliers:</h1>

<div id="mainsuppliers">
  <% @mainsuppliers.each do |mainsupplier| %>
    <%= render mainsupplier %>
    <p>
      <%= link_to "Show this supplier", mainsupplier %>
    </p>
  <% end %>
</div>

<%= link_to "New supplier", new_mainsupplier_path %>

app/views/mainsuppliers/new.html.erb
<h1>New mainsupplier</h1>

<%= render "form", mainsupplier: @mainsupplier %>

<br>

<div>
  <%= link_to "Back to suppliers", mainsuppliers_path %>
</div>

app/views/mainsuppliers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @mainsupplier %>

<div>
  <%= link_to "Edit this supplier", edit_mainsupplier_path(@mainsupplier) %> |
  <%= link_to "Back to suppliers", mainsuppliers_path %>

  <%= button_to "Destroy this supplier", @mainsupplier, method: :delete %>
</div>

app/views/managers/beers.html.erb
<h2>Available beers:</h1>

<% @beers.each do |beer| %>
    <p><%= beer['name'] %></p>
<% end %>

app/views/managers/fruits.html.erb
<h1>Available fruits:</h1>

<% @fruits.each do |fruit| %>
    <p><%= fruit['name'] %></p>
<% end %>

app/views/managers/index.html.erb
<% if current_user %>
    <p>Hello <%= current_user.email %></p>
    <p>You are a <%= current_user.role%></p>
<% end %>

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>One Page Wonder - Start Bootstrap Template</title>
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
    </head>
    <body id="page-top">
        <!-- Header-->
        <header class="masthead text-center text-white">
            <div class="masthead-content">
                <div class="container px-5">
                    <h1 class="masthead-heading mb-0">Inventory Manager</h1>
                    <h2 class="masthead-subheading mb-0">Welcome</h2>
                </div>
            </div>
            <div class="bg-circle-1 bg-circle"></div>
            <div class="bg-circle-2 bg-circle"></div>
            <div class="bg-circle-3 bg-circle"></div>
            <div class="bg-circle-4 bg-circle"></div>
        </header>
        <!-- Footer-->
        <footer class="py-5 bg-black">
            <div class="container px-5"><p class="m-0 text-center text-white small">Copyright &copy; Inventory manager 2022</p></div>
        </footer>
    </body>
</html>

app/views/managers/mainsuppliers.html.erb
<h3>Main suppliers:</h3>